# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Portfolio"
license = "MIT"
licenselink = "https://github.com/takameron/hugo_theme_portfolio/blob/main/LICENSE"
description = "Portfolio"
homepage = "https://github.com/takameron/hugo_theme_portfolio"
tags = ["portfolio"]
features = []
min_version = "0.113.0"

[author]
  name = "takameron"
  homepage = "https://portfolio.takameron.info/"
